#
# Example configuration file for virtual-kubelet AWS Fargate provider.
#
# Usage:
# virtual-kubelet --provider aws --provider-config fargate.toml
#

# AWS region where Fargate resources are provisioned. Mandatory.
Region = "us-east-1"

# Fargate cluster name. Optional. Defaults to "default".
# If a cluster with this name does not exist in the region, virtual-kubelet will create it.
# Although the same Fargate cluster can be shared by multiple virtual-kubelets,
# we recommend to create a dedicated Fargate cluster for each virtual-kubelet.
ClusterName = "fargate1"

# List of subnets that pods are connected to. Mandatory.
Subnets = ["subnet-12345678"]

# List of security groups for pods. Optional.
# If omitted, pods inherit their VPC's default security group.
SecurityGroups = ["sg-12345678", "sg-87654321"]

# Whether pod ENIs are assigned a public IPv4 address. Optional. Defaults to false.
AssignPublicIPv4Address = false

# Role assumed by AWS Fargate to execute your task. Optional.
# https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_execution_IAM_role.html
ExecutionRoleArn = ""

# AWS CloudWatch Log Group Name used to store container logs. Optional.
# If omitted, no container logs will be stored and retrievable.
CloudWatchLogGroupName = "/ecs/virtual-kubelet-logs"

# Fargate platform version. Optional. Defaults to "LATEST".
# https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform_versions.html
PlatformVersion = "LATEST"

# Operating system for pods. Optional. Defaults to "Linux".
OperatingSystem = "Linux"

# Fargate capacity advertised by virtual-kubelet. Optional. Defaults to the values below.
# Capacity is specified using Kubernetes resource format.
# https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
CPU = "20"
Memory = "40Gi"
Pods = "20"
